#!/bin/sh

SRC=$SRCDIR/paste-py
tmp=$SRC/.dest

deps() {
	which git || exit 1
}

fetch() {
	cd $SRCDIR
	git clone https://github.com/acieroid/paste-py.git
	mkdir -p $tmp
}

build() {
	mkdir -p $tmp/usr/bin
	cp $SRC/paste.sh $tmp/usr/bin
}

mkpkg() {
	cd $tmp
	PATH=$PATH:/sbin/:/usr/sbin fakerootns makepkg -c n $PKGDIR/paste-py-git.txz
}

clean() {
	rm -rf $tmp
}
